version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
    volumes:
      - data:/data/db

  server:
    image: ghcr.io/bortexel/stats-server:latest
    depends_on: [ 'mongo' ]
    restart: always
    environment:
      MONGO_CONNECTION_URI: mongodb://root:root-password@mongo:27017
      MUTATION_KEY: super-secret-key
    ports: [ '7474:8080' ]

volumes:
  data:
