version: '3'
services:
  website:
    image: registry.ruscalworld.ru/bortexel/stats-server:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_CONNECTION_URI: mongodb://stats:replace-this@mongo:27017/
      MUTATION_KEY: ''
    ports:
      - '7070:8080'
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: stats
      MONGO_INITDB_ROOT_PASSWORD: replace-this
volumes:
  mongo-data:
