// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/bortexel/stats-server/models"
)

type AdvancementDisplay struct {
	Tab   *string `json:"tab"`
	Type  *string `json:"type"`
	Icon  *string `json:"icon"`
	Title *string `json:"title"`
}

type AdvancementInput struct {
	Key  string `json:"key"`
	Done bool   `json:"done"`
}

type UpdatePlayer struct {
	Server       string              `json:"server"`
	UUID         string              `json:"uuid"`
	Name         string              `json:"name"`
	Stats        *models.StatsInput  `json:"stats"`
	Advancements []*AdvancementInput `json:"advancements"`
}
